# Generated by Django 5.2.10 on 2026-03-13 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
